
const Users = [
    {
        id: 0,
        userName: 'waqas',
        userEmail: 'muhammadwaqas@gmail.com',
        userStatus: 'Active',
        userGender: 'Male',
        userPhone: '03222946642',
        userPassword: '@$vfrdesw5',
        userZipcode: '032589',
        userCountry: 'pakistan',
        userState: 'sindh',
        userCity: 'karachi',
        userSignupDate: '01-01-2022',
        userType: ['normalUser', 'standardUser', 'businessUser'],
    },
    {
        id: 1,
        userName: 'fatima',
        userEmail: 'fatimakhan@gmail.com',
        userStatus: 'Inactive',
        userGender: 'Female',
        userPhone: '03338523691',
        userPassword: '%^852369hgb@',
        userZipcode: '951357',
        userCountry: 'pakistan',
        userState: 'sindh',
        userCity: 'karachi',
        userSignupDate: '05-02-2022',
        userType: ['normalUser', 'standardUser'],
    },
    {
        id: 2,
        userName: 'waseem',
        userEmail: 'waseemkhan@gmail.com',
        userStatus: 'Active',
        userGender: 'Male',
        userPhone: '03218523691',
        userPassword: '258369#$jm',
        userZipcode: '001478',
        userCountry: 'India',
        userState: 'up',
        userCity: 'kolkata',
        userSignupDate: '16-02-2022',
        userType: ['normalUser'],
    },
    {
        id: 3,
        userName: 'ali',
        userEmail: 'alikhan@gmail.com',
        userStatus: 'Inactive',
        userGender: 'Male',
        userPhone: '03008523691',
        userPassword: '$%CD852369',
        userZipcode: '369843',
        userCountry: 'pakistan',
        userState: 'sindh',
        userCity: 'karachi',
        userSignupDate: '20-01-2022',
        userType: ['normalUser', 'standardUser'],
    },
    {
        id: 4,
        userName: 'zeeshan',
        userEmail: 'zeeshanAhmed@gmail.com',
        userStatus: 'Active',
        userGender: 'Male',
        userPhone: '03968523691',
        userPassword: 'ER%$951357',
        userZipcode: '665741',
        userCountry: 'pakistan',
        userState: 'sindh',
        userCity: 'karachi',
        userSignupDate: '25-02-2022',
        userType: ['normalUser'],
    },
    {
        id: 5,
        userName: 'saima',
        userEmail: 'saimakhan@gmail.com',
        userStatus: 'Inactive',
        userGender: 'Female',
        userPhone: '03459632581',
        userPassword: 'ikjuyh$#95',
        userZipcode: '039751',
        userCountry: 'pakistan',
        userState: 'sindh',
        userCity: 'karachi',
        userSignupDate: '26-02-2022',
        userType: ['normalUser', 'standardUser', 'businessUser'],
    }
];


export default Users;